### ISSUE TITLE
Implementation of Elkapod orientation system with Kalman Filter on STM32

### ISSUE THREAD

**Issue by VisteK528** [HexapodBionik/ElkapodHardwareController_software#1]

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by VisteK528** [comment]
I decided to better calibrate the IMU sensor so that the raw data before filtering will be of greater quality.
For the purpose of the calibration I mounted the PCB flat on the leveled table and measured acceleration, gyro and euler data for about 60 sec which resulted in more than 20000 samples.

To check if the calibration was successful I measured the MSE and MEAN of the euler angles before and after the calibration.
# Pre calibration
$MSE_{\text{roll}} = 0.0891$
$MSE_{\text{pitch}} = 0.5673$

$MEAN_{\text{roll}} = -0.23544 \deg$
$MEAN_{\text{pitch}} = -0.7325806 \deg$

# Post calibration
$MSE_{\text{roll}} = 0.0316$
$MSE_{\text{pitch}} = 0.0297$

$MEAN_{\text{roll}} = 0.003762 \deg$
$MEAN_{\text{pitch}} = -0.001179 \deg$

I think the results are quite satisfying. Here you can see the euler angles before and after the calibration on the plot.
# Before
![Image](https://github.com/user-attachments/assets/63db524f-7d4d-40b7-a39b-3cbb6ed40767)

# After

![Image](https://github.com/user-attachments/assets/2a4b02cf-71fb-4a4a-8861-9ff376966f85)


# Accelerometer offsets

$a_x = a_{x\text{raw}} + b_x$
$a_y = a_{y\text{raw}} + b_y$
$a_z = a_{z\text{raw}} + b_z$

where 

$b_x = -0.04008$
$b_y = 0.01267$
$b_z = -0.0189003$

**Comment by VisteK528** [comment]
Here you can see the results of almost calibrated Kalman Filter working on data from previously calibrated IMU. I also uploaded the data I was working on.

[accel_data_2.csv](https://github.com/user-attachments/files/16852556/accel_data_2.csv)
[gyro_data_2.csv](https://github.com/user-attachments/files/16852555/gyro_data_2.csv)
[orientation_data_2.csv](https://github.com/user-attachments/files/16852557/orientation_data_2.csv)



![Image](https://github.com/user-attachments/assets/7fa42c1c-84a2-4454-b749-aa9f0df524fc)

**Comment by VisteK528** [comment]
I was thinking if more optimization is needed for the orientation estimation using Kalman Filter such as getting rid of the Eigen library in favour of replacing matrix multiplications by simple multiplications on raw arrays, but after some measurements I think the performance of the code using Eigen library, especialy when compiled with **-Ofast** optimization is furiously fast -> loop is executed in $72 \mu s$.
